exhibitions/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    path('galleries/', views.galleries, name="Galleries"),
    path('exhibitions/', views.exhibitions, name="Exhibitions"),
    path('gallery/<int:gallery_id>', views.gallery, name="Gallery"),
    path('exhibition/<int:exhibition_id>', views.exhibition, name="Exhibition"),
    path('item/<int:item_id>', views.item, name="Item"),
    path('search_organisms/', views.search_organisms, name="Search Organisms"),
    path('search_artifacts/', views.search_artifacts, name="Search Artifacts"),
    path('search_fossils/', views.search_fossils, name="Search Fossils"),
    path('search_artworks/', views.search_artworks, name="Search Artworks"),
    path('', views.index, name='index')
]

museum_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('exhibitions.urls')),
]

exhibitions/models.py
from django.db import models
from model_utils.managers import InheritanceManager

CONDITION_CHOICES = [
    (1, ("Preserved"),),
    (2, ("Fair"),),
    (3, ("Damaged"),)
]

CONDITION_CHOICES_ORGANISM = [
    (1, ("Live"),),
    (2, ("Taxidermied"),)
]

class Gallery(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Galleries"

class Exhibition(models.Model):
    name = models.CharField(max_length=100)
    sponsor = models.CharField(max_length=100)
    start_date = models.DateField('Date exhibition starts')
    end_date = models.DateField('Date exhibition ends')
    active = models.BooleanField()
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField('Item description')
    exhibition = models.ForeignKey(Exhibition, on_delete=models.CASCADE)

    # Manage inheritance (one-to-one Item types)
    objects = InheritanceManager()

    def __str__(self):
        return self.name

class Artifact(Item):
    country_origin = models.CharField(max_length=100)
    excavation_site = models.CharField(max_length=150)
    discovery_year = models.IntegerField('Year artifact was discovered')
    condition = models.IntegerField(choices=CONDITION_CHOICES)
    material = models.CharField(max_length=50)

class Organism(Item):
    scientific_name = models.CharField(max_length=100)
    condition = models.IntegerField(choices=CONDITION_CHOICES_ORGANISM)

class Fossil(Item):
    country_origin = models.CharField(max_length=100)
    excavation_site = models.CharField(max_length=150)
    discovery_year = models.IntegerField('Year fossil was discovered')
    period = models.CharField(max_length=50)

class Artwork(Item):
    art_type = models.CharField(max_length=50)
    author = models.CharField(max_length=100)
    year = models.IntegerField()

class Staff(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=50)
    shift = models.CharField('Day or Night shift', max_length=50)

    works_in = models.ManyToManyField(Gallery)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Staff"

exhibitions/forms.py
import datetime

from django import forms
from .models import CONDITION_CHOICES, CONDITION_CHOICES_ORGANISM

CONDITION_CHOICES_FORM = [(0, (""),)] + CONDITION_CHOICES
CONDITION_CHOICES_FORM_ORGANISM = [(0, (""),)] + CONDITION_CHOICES_ORGANISM

class SearchArtifactsForm(forms.Form):
    name = forms.CharField(label="Name", max_length=100, required=False)
    origin = forms.CharField(label="Country of Origin", max_length=100, required=False)
    excavation_site = forms.CharField(label="Excavation Site", max_length=150, required=False)
    discovery_year = forms.IntegerField(label="Disovery Year", min_value=1500, max_value=2018, required=False)
    condition = forms.ChoiceField(label="Condition", choices = CONDITION_CHOICES_FORM, initial='', required=False)
    material = forms.CharField(label="Material", max_length=50, required=False)


class SearchFossilForm(forms.Form):
    name = forms.CharField(label="Name", max_length=100, required=False)
    origin = forms.CharField(label="Country of Origin", max_length=100, required=False)
    excavation_site = forms.CharField(label="Excavation Site", max_length=150, required=False)
    discovery_year = forms.IntegerField(label="Disovery Year", min_value=1500, max_value=2018, required=False)
    period = forms.CharField(label="Period", max_length=50, required=False)

class SearchOrganismForm(forms.Form):
    name = forms.CharField(label="Name", max_length=100, required=False)
    scientific_name = forms.CharField(label="Scientific Name", max_length=100, required=False)
    condition = forms.ChoiceField(label="Condition", choices = CONDITION_CHOICES_FORM_ORGANISM, initial='', required=False)

class SearchArtworkForm(forms.Form):
    name = forms.CharField(label="Name", max_length=100, required=False)
    art_type = forms.CharField(label="Style", max_length=50, required=False)
    author = forms.CharField(label="Author", max_length=100, required=False)
    year = forms.IntegerField(label="Year", min_value=1, max_value=2018, required=False)

exhibitions/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.db.models import Func, F
from django.views.decorators.cache import cache_page

from .forms import SearchArtifactsForm, SearchArtworkForm, SearchFossilForm, SearchOrganismForm
from .models import *

def index(request):
    return render(request, 'exhibitions/index.html', {})

def galleries(request):
    galleries = Gallery.objects.all()
    gallery_exhibitions = []

    for g in galleries:
        gallery_exhibitions.append((g, list(Exhibition.objects.filter(gallery=g))))

    return render(request, 'exhibitions/galleries.html', {"galleries": gallery_exhibitions})

def exhibitions(request):
    exhibitions = Exhibition.objects.all()
    exhibition_items = []

    for e in exhibitions:
        exhibition_items.append((e, list(Item.objects.filter(exhibition=e)[:10])))
    
    return render(request, 'exhibitions/exhibitions.html', {"exhibitions": exhibition_items})

def gallery(request, gallery_id):
    if Gallery.objects.filter(pk=gallery_id).exists():
        g = Gallery.objects.get(pk=gallery_id)
    else:
        raise Http404("Item not found")

    exhibitions = Exhibition.objects.filter(gallery=g)

    return render(request, 'exhibitions/gallery.html', {"gallery": g, "exhibitions": exhibitions})

@cache_page(60 * 15)
def exhibition(request, exhibition_id):
    if Exhibition.objects.filter(pk=exhibition_id).exists():
        e = Exhibition.objects.get(pk=exhibition_id)
    else:
        raise Http404("Item not found")

    items = list(Item.objects.filter(exhibition=e).order_by('name'))

    return render(request, 'exhibitions/exhibition.html', {"exhibition": e, "items": items})

@cache_page(60 * 30)
def item(request, item_id):
    if Item.objects.filter(pk=item_id).exists():
        item = Item.objects.get_subclass(pk=item_id)
    else:
        raise Http404("Item not found")

    def name_similarity(name1, name2):
        if name1 in name2 or name2 in name1:
            return 0

        diff = abs(len(name2) - len(name1))
        for i in range(min(len(name1), len(name2))):
            if name1.lower()[i] != name2.lower()[i]:
                diff += 1
        
        return diff

    suggested = []

    if isinstance(item, Artifact):
        partial_list = Artifact.objects.extra(select={'abs_diff': 'ABS(`discovery_year` - %s)',}, select_params=(item.discovery_year,)).order_by('abs_diff').exclude(pk=item.pk)[:100]
        suggested = list(map(list, zip([0 for i in range(len(partial_list))], partial_list)))
        
        for i in range(len(suggested)):
            item2 = suggested[i][1]

            name_score = name_similarity(item.name, item2.name)
            exhibition_score = 1 if item.exhibition.pk != item2.exhibition.pk else 0
            
            origin_score = 1 if item.country_origin != item2.country_origin else 0
            excavation_score = 1 if item.excavation_site != item2.excavation_site else 0
            year_score = abs(item.discovery_year - item2.discovery_year)
            condition_score = 1 if item.condition != item2.condition else 0
            material_score = 1 if item.material != item2.material else 0

            total_score = name_score + (exhibition_score * 2)
            total_score += (origin_score * 5) + (year_score // 2)
            total_score += (condition_score * 3) + (material_score * 2)
            suggested[i][0] = total_score

        suggested = list(sorted(suggested, key=lambda tup: tup[0]))[:10]

    elif isinstance(item, Organism):
        suggested = list(map(list, zip([0 for i in range(Organism.objects.all().count())], Organism.objects.all().exclude(pk__exact=item.pk))))

        for i in range(len(suggested)):
            item2 = suggested[i][1]

            name_score = name_similarity(item.name, item2.name)
            exhibition_score = 1 if item.exhibition.pk != item2.exhibition.pk else 0
            
            sci_name_score = 1 if item.scientific_name != item2.scientific_name else 0
            condition_score = 1 if item.condition != item2.condition else 0

            total_score = name_score + (exhibition_score * 2)
            total_score += sci_name_score + (condition_score * 2)
            suggested[i][0] = total_score

        suggested = list(sorted(suggested, key=lambda tup: tup[0]))[:10]

    elif isinstance(item, Fossil):
        partial_list = Fossil.objects.extra(select={'abs_diff': 'ABS(`discovery_year` - %s)',}, select_params=(item.discovery_year,)).order_by('abs_diff').exclude(pk=item.pk)[:100]
        suggested = list(map(list, zip([0 for i in range(len(partial_list))], partial_list)))

        for i in range(len(suggested)):
            item2 = suggested[i][1]

            name_score = name_similarity(item.name, item2.name)
            exhibition_score = 1 if item.exhibition.pk != item2.exhibition.pk else 0
            
            origin_score = 1 if item.country_origin != item2.country_origin else 0
            excavation_score = 1 if item.excavation_site != item2.excavation_site else 0
            year_score = abs(item.discovery_year - item2.discovery_year)
            period_score = 1 if item.period != item2.period else 0

            total_score = name_score + (exhibition_score * 2)
            total_score += (origin_score * 5) + (year_score // 2)
            total_score += (period_score * 10)
            suggested[i][0] = total_score

        suggested = list(sorted(suggested, key=lambda tup: tup[0]))[:10]

    elif isinstance(item, Artwork):
        partial_list = Artwork.objects.extra(select={'abs_diff': 'ABS(`year` - %s)',}, select_params=(item.year,)).order_by('abs_diff').exclude(pk=item.pk)[:100]
        suggested = list(map(list, zip([0 for i in range(len(partial_list))], partial_list)))

        for i in range(len(suggested)):
            item2 = suggested[i][1]

            name_score = name_similarity(item.name, item2.name)
            exhibition_score = 1 if item.exhibition.pk != item2.exhibition.pk else 0
            
            type_score = 1 if item.art_type != item2.art_type else 0
            author_score = 1 if item.author != item2.author else 0
            year_score = abs(item.year - item2.year)

            total_score = name_score + (exhibition_score * 2)
            total_score += (type_score * 5) + (year_score // 2)
            total_score += (author_score * 5)
            suggested[i][0] = total_score

        suggested = list(sorted(suggested, key=lambda tup: tup[0]))[:10]
    
    return render(request, "exhibitions/item.html", {"item": item, "type": item.__class__.__name__, "suggestions": suggested})

def search_artifacts(request):
    if request.method == 'POST':
        form = SearchArtifactsForm(request.POST)

        if form.is_valid():
            results = Artifact.objects.all()

            if form.cleaned_data["name"]:
                results = results.filter(name__icontains=form.cleaned_data["name"])
            
            if form.cleaned_data["origin"]:
                results = results.filter(country_origin__icontains=form.cleaned_data["origin"])

            if form.cleaned_data["excavation_site"]:
                results = results.filter(excavation_site__icontains=form.cleaned_data["excavation_site"])

            if form.cleaned_data["discovery_year"]:
                results = results.filter(discovery_year__exact=form.cleaned_data["discovery_year"])
            
            if form.cleaned_data["condition"] != '0':
                results = results.filter(condition__exact=int(form.cleaned_data["condition"]))

            if form.cleaned_data["material"]:
                results = results.filter(material__iexact=form.cleaned_data["material"])

            return render(request, 'exhibitions/search_artifacts.html', {'form': form, 'results': results[:250]})
    else:
        form = SearchArtifactsForm()

    return render(request, 'exhibitions/search_artifacts.html', {'form': form, 'results':{}})

def search_artworks(request):
    if request.method == 'POST':
        form = SearchArtworkForm(request.POST)

        if form.is_valid():
            results = Artwork.objects.all()

            if form.cleaned_data["name"]:
                results = results.filter(name__icontains=form.cleaned_data["name"])

            if form.cleaned_data["year"]:
                results = results.filter(year__exact=form.cleaned_data["year"])
            
            if form.cleaned_data["author"]:
                results = results.filter(author__icontains=form.cleaned_data["author"])

            if form.cleaned_data["art_type"]:
                results = results.filter(art_type__icontains=form.cleaned_data["art_type"])

            return render(request, 'exhibitions/search_artworks.html', {'form': form, 'results': results[:250]})
    else:
        form = SearchArtworkForm()

    return render(request, 'exhibitions/search_artworks.html', {'form': form, 'results':{}})

def search_fossils(request):
    if request.method == 'POST':
        form = SearchFossilForm(request.POST)

        if form.is_valid():
            results = Fossil.objects.all()

            if form.cleaned_data["name"]:
                results = results.filter(name__icontains=form.cleaned_data["name"])
            
            if form.cleaned_data["origin"]:
                results = results.filter(country_origin__icontains=form.cleaned_data["origin"])

            if form.cleaned_data["excavation_site"]:
                results = results.filter(excavation_site__icontains=form.cleaned_data["excavation_site"])

            if form.cleaned_data["discovery_year"]:
                results = results.filter(discovery_year__exact=form.cleaned_data["discovery_year"])

            if form.cleaned_data["period"]:
                results = results.filter(period__icontains=form.cleaned_data["period"])

            return render(request, 'exhibitions/search_fossils.html', {'form': form, 'results': results[:250]})
    else:

exhibitions/templates/exhibitions/base.html
{% load static %}
<html>
    <head>
        <title>Museum</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Museum</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Index
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="/galleries/">Galleries</a>
                                <a class="dropdown-item" href="/exhibitions/">Exhibitions</a>
                            </div>
                        </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Search
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/search_artifacts/">Artifacts</a>
                            <a class="dropdown-item" href="/search_organisms/">Organisms</a>
                            <a class="dropdown-item" href="/search_fossils/">Fossils</a>
                            <a class="dropdown-item" href="/search_artworks/">Artworks</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        
        <div class="container" style="padding-top: 10pt">
            {% block content %}
            {% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

exhibitions/templates/exhibitions/exhibition.html
{% extends 'exhibitions/base.html' %}

{% block content %}
    
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/gallery/{{ exhibition.gallery.pk }}">{{ exhibition.gallery.name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ exhibition.name }}</li>
        </ol>
    </nav>

    <h3>{{ exhibition.name }}</h3>

    <ul>
        {% for i in items %}
            <li><a href="/item/{{ i.pk }}">{{ i.name }}</a></li>
        {% endfor %}
    </ul>
    
    <hr>

{% endblock %}

exhibitions/templates/exhibitions/exhibitions.html
{% extends 'exhibitions/base.html' %}

{% block content %}
    
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/galleries/">Galleries</a></li>
            <li class="breadcrumb-item active" aria-current="page">Exhibitions</li>
        </ol>
    </nav>

    <h1>Our Exhibitions</h1>

    {% for e, items in exhibitions %}
        
        <h3>
            {{ e.name }}
            <small class="text-muted">At Gallery {{ e.gallery.name }}</small>
        </h3>

        <ul>
            {% for i in items %}
                <li><a href="/item/{{ i.pk }}">{{ i.name }}</a></li>
            {% endfor %}
        </ul>

        <hr>

    {% endfor %}

{% endblock %}

exhibitions/templates/exhibitions/galleries.html
{% extends 'exhibitions/base.html' %}

{% block content %}
    
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Our Galleries</li>
        </ol>
    </nav>

    <h1>The Museum Galleries</h1>

    {% for g, exhibitions in galleries %}
        <h3>{{ g.name }}</h3>

        <ul>
            {% for e in exhibitions %}
                <li><a href="/exhibition/{{ e.pk }}">{{ e.name }}</a></li>
            {% endfor %}
        </ul>

        <hr>

    {% endfor %}

{% endblock %}

exhibitions/templates/exhibitions/gallery.html
{% extends 'exhibitions/base.html' %}

{% block content %}
    
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">{{ gallery.name }}</li>
        </ol>
    </nav>

    <h3>{{ gallery.name }}</h3>

    <ul>
        {% for e in exhibitions %}
            <li><a href="/exhibition/{{ e.pk }}">{{ e.name }}</a></li>
        {% endfor %}
    </ul>

    <hr>
    
{% endblock %}

exhibitions/templates/exhibitions/index.html
{% extends 'exhibitions/base.html' %}

{% block content %}
    <h1>Welcome to our Museum!</h1>

{% endblock %}

exhibitions/templates/exhibitions/item.html
{% extends 'exhibitions/base.html' %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/gallery/{{ item.exhibition.gallery.pk }}">{{ item.exhibition.gallery.name }}</a></li>
            <li class="breadcrumb-item"><a href="/exhibition/{{ item.exhibition.pk }}">{{ item.exhibition.name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ item.name }}</li>
        </ol>
    </nav>

    <p>
        <h1>
            {{ item.name }}
            <small class="text-muted">{{ type }}</small>
        </h1>
    </p>

    <div class="alert alert-light">
        {{ item.description }}
    </div>

    <div style='display:inline-block; width: 30%; float: left; word-wrap: break-word'>
        {% if type == "Artifact" %}
            <p class="font-weight-bold">Country of Origin: </p><p>{{ item.country_origin }}</p>
            <p class="font-weight-bold">Excavation Site: </p><p>{{ item.excavation_site }}</p>
            <p class="font-weight-bold">Discovery Year: </p><p>{{ item.discovery_year }}</p>
            <p class="font-weight-bold">Condition: </p><p>{{ item.get_condition_display }}</p>
            <p class="font-weight-bold">Material: </p><p>{{ item.material }}</p>
        {% elif type == "Organism" %}
            <p class="font-weight-bold">Scientific Name: </p><p>{{ item.scientific_name }}</p>
            <p class="font-weight-bold">Condition: </p><p>{{ item.get_condition_display }}</p>
        {% elif type == "Fossil" %}
            <p class="font-weight-bold">Country of Origin: </p><p>{{ item.country_origin }}</p>
            <p class="font-weight-bold">Excavation Site: </p><p>{{ item.excavation_site }}</p>
            <p class="font-weight-bold">Discovery Year: </p><p>{{ item.discovery_year }}</p>
            <p class="font-weight-bold">Period: </p><p>{{ item.period }}</p>
        {% elif type == "Artwork" %}
            <p class="font-weight-bold">Type: </p><p>{{ item.art_type }}</p>
            <p class="font-weight-bold">Author: </p><p>{{ item.author }}</p>
            <p class="font-weight-bold">From: </p><p>{{ item.year }}</p>
        {% endif %}
    </div>

    <div style='display:inline-block; width: 70%; float: right;'>
        <h3>Similar Items</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    {% if type == "Artifact" %}
                        <th>Origin</th>
                        <th>Discovery Year</th>
                        <th>Condition</th>
                        <th>Material</th>

                    {% elif type == "Organism" %}
                        <th>Scientific Name</th>
                        <th>Condition</th>

                    {% elif type == "Fossil" %}
                        <th>Origin</th>
                        <th>Discovery Year</th>
                        <th>Period</th>

                    {% elif type == "Artwork" %}
                        <th>Type</th>
                        <th>Author</th>
                        <th>Date</th>
                    {% endif %}

                    <th>Exhibition</th>
                </tr>
            </thead>
    
            <tbody>
            
                {% for _, s in suggestions %}
                    <tr>
                        <th scope="row"><a href="/item/{{ s.pk }}">{{ s.name }}</a></th>

                        {% if type == "Artifact" %}
                            <th>{{ s.country_origin }}</th>
                            <th>{{ s.discovery_year }}</th>
                            <th>{{ s.get_condition_display }}</th>
                            <th>{{ s.material }}</th>

                        {% elif type == "Organism" %}
                            <th>{{ s.scientific_name }}</th>
                            <th>{{ s.condition }}</th>

                        {% elif type == "Fossil" %}
                            <th>{{ s.country_origin }}</th>
                            <th>{{ s.discovery_year }}</th>
                            <th>{{ s.period}}</th>

                        {% elif type == "Artwork" %}
                            <th>{{ s.art_type }}</th>
                            <th>{{ s.author }}</th>
                            <th>{{ s.year }}</th>
                        {% endif %}
                        
                        <th><a href="/exhibition/{{ s.exhibition.pk }}">{{ s.exhibition.name }}</a></th>
                    </tr>
                {% endfor %}
    
            </tbody>
        </table>
    </div>

{% endblock %}

exhibitions/templates/exhibitions/search_artifacts.html
{% extends 'exhibitions/base.html' %}

{% block content %}
    <form action="/search_artifacts/" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Search"/>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Discovery Year</th>
                <th>Condition</th>
                <th>Material</th>
                <th>Exhibition</th>
            </tr>
        </thead>

        <tbody>
        
            {% for result in results %}
                <tr>
                    <th scope="row"><a href="/item/{{ result.pk }}">{{ result.name }}</a></th>
                    <th>{{ result.discovery_year }}</th>
                    <th>{{ result.get_condition_display }}</th>
                    <th>{{ result.material }}</th>
                    <th><a href="/exhibition/{{ result.exhibition.pk }}">{{ result.exhibition }}</a></th>
                </tr>
            {% endfor %}

        </tbody>
    </table>

{% endblock %}

exhibitions/templates/exhibitions/search_artworks.html
{% extends 'exhibitions/base.html' %}

{% block content %}
    <form action="/search_artworks/" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Search"/>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Author</th>
                <th>Style</th>
                <th>Year</th>
                <th>Exhibition</th>
            </tr>
        </thead>

        <tbody>
        
            {% for result in results %}
                <tr>
                    <th scope="row"><a href="/item/{{ result.pk }}">{{ result.name }}</a></th>
                    <th>{{ result.author }}</th>
                    <th>{{ result.art_type }}</th>
                    <th>{{ result.year }}</th>
                    <th><a href="/exhibition/{{ result.exhibition.pk }}">{{ result.exhibition }}</a></th>
                </tr>
            {% endfor %}

        </tbody>
    </table>

{% endblock %}

exhibitions/templates/exhibitions/search_fossils.html
{% extends 'exhibitions/base.html' %}

{% block content %}
    <form action="/search_fossils/" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Search"/>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Discovery Year</th>
                <th>Period</th>
                <th>Exhibition</th>
                
            </tr>
        </thead>

        <tbody>
        
            {% for result in results %}
                <tr>
                    <th scope="row"><a href="/item/{{ result.pk }}">{{ result.name }}</a></th>
                    <th>{{ result.discovery_year }}</th>
                    <th>{{ result.period }}</th>
                    <th><a href="/exhibition/{{ result.exhibition.pk }}">{{ result.exhibition }}</a></th>
                    
                </tr>
            {% endfor %}

        </tbody>
    </table>

{% endblock %}

exhibitions/templates/exhibitions/search_organisms.html
{% extends 'exhibitions/base.html' %}

{% block content %}
    <form action="/search_organisms/" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Search"/>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Scientific Name</th>
                <th>Condition</th>
                <th>Exhibition</th>
     
            </tr>
        </thead>

        <tbody>
        
            {% for result in results %}
                <tr>
                    <th scope="row"><a href="/item/{{ result.pk }}">{{ result.name }}</a></th>
                    <th>{{ result.scientific_name }}</th>
                    <th>{{ result.get_condition_display }}</th>
                    <th><a href="/exhibition/{{ result.exhibition.pk }}">{{ result.exhibition }}</a></th>
                    
                </tr>
            {% endfor %}

        </tbody>
    </table>

{% endblock %}